"""added last updated

Revision ID: 02106affc5f9
Revises: 
Create Date: 2020-08-04 08:32:19.121671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02106affc5f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_packages_updated_date'), 'packages', ['updated_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packages_updated_date'), table_name='packages')
    op.drop_column('packages', 'updated_date')
    # ### end Alembic commands ###
