"""added last updated

Revision ID: b2d07b72e3a2
Revises: 02106affc5f9
Create Date: 2020-08-06 08:53:05.374526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d07b72e3a2'
down_revision = '02106affc5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('package_id', sa.String(), nullable=True),
    sa.Column('release_id', sa.BigInteger(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloads_created_date'), 'downloads', ['created_date'], unique=False)
    op.create_index(op.f('ix_downloads_package_id'), 'downloads', ['package_id'], unique=False)
    op.create_index(op.f('ix_downloads_release_id'), 'downloads', ['release_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downloads_release_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_package_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_created_date'), table_name='downloads')
    op.drop_table('downloads')
    # ### end Alembic commands ###
